PREFIX crdn: <https://my.url/metamodels/coordination#>
PREFIX trans: <https://my.url/transformations/>

CONSTRUCT {
    ?eventloop trans:has-events ?event .
}
WHERE {
    ?eventloop a crdn:EventLoop ;
        ^crdn:event-loop / crdn:events ?event .
}